server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  profiles:
    active: native #设置为本地启动的方式，而不是通过git  
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
management:
  security:
    enabled: false
