server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway #注册进微服务里面的名字  注册 注册 注册
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    
zuul: 
  prefix: /SAMSUNG   #统一公共路径前缀  域名管理安全加固
  ignored-services: "*" #封口子microservicecloud-dept   禁用掉全部微服务真是路径  全部 必须经过zuul网关虚拟路径访问
  routes: #隐藏暴露微服务名字
  #网关地址+eureka服务访问
    mydept.serviceId: microservicecloud-dept  #用mydept.path代替  做了真实虚拟映射
    mydept.path: /S8/** 
 
info:
  app.name: llb-microcloud
  company.name: www.llb.com
  build.artifactId: microservicecloud-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT