spring.application.name: microcloud-gateway
server.port: 9528

eureka.client.serviceUrl.defaultZone: http://localhost:7004/eureka/

# 网关配置
spring:
  cloud:
    gateway:
      routes:
        # 路由到示例项目的spring-cloud-producer模块  #分为三个  由id带领
      - id: hello_route
        uri: http://localhost:9529
        predicates:
        - Path=/producer/**
        filters:
        - StripPrefix=3
        # 集成eureka注册中心的配置示例
      - id: hello_ribbon_route
        uri: lb://micro-gateway-provider  #查询eurka实例
        predicates:
        - Path=/eureka-micro/**
        filters:
        - StripPrefix=2
        # 路由到百度页面
      - id: baidu_route
        uri: http://www.baidu.com
        predicates:
        - Path=/baidu/**
        filters:
        - StripPrefix=3
