 
server:
  port: 80
spring:
 application:
    name: service-feign
hystrix.command.default.execution.isolation.strategy: SEMAPHORE 
feign: 
  hystrix: 
    enabled: true
    command:
     default:
      execution:
        isolation:
          strategy: SEMAPHORE    
ribbon.eureka.enable: true 
eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

#RestTemplate访问服务端的时候自带负载均衡 访问集群
