server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway #注册进微服务里面的名字  注册 注册 注册
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    
zuul: 
  prefix: /cloud   #统一公共路径前缀  域名管理安全加固
  ignored-services: "*" #封口子microservicecloud-dept   禁用掉全部微服务真是路径  全部 必须经过zuul网关虚拟路径访问
  routes: #隐藏暴露微服务名字
  #网关地址+eureka服务访问
    api-a:
      path: /api-a/**
      serviceId: microservicecloud-dept
    api-b:
      path: /api-b/**
      serviceId: microservicecloud-dept02
 
info:
  app.name: llb-microcloud
  company.name: www.llb.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$